backend:
  name: github
  repo: Namrajp/my-new-astro-blog
  branch: main
  base_url: https://learncodingfirst.com

media_folder: "public/images"
public_folder: "/images"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    summary: "{{title}} — {{date}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        pattern: ['^.+$', "Title is required"]
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false
      - label: "Description"
        name: "description"
        widget: "string"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
        min: 1
      - label: "Status"
        name: "status"
        widget: "select"
        options:
          - { label: "Published", value: "published" }
          - { label: "Draft", value: "draft" }
        default: "published"
      - label: "Body"
        name: "body"
        widget: "markdown"